import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import Navbar from "./components/navbar";
=======
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
>>>>>>> 1b51ae8ea8e08596ad8bbed7460a51867efd4679

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
<<<<<<< HEAD
  title: "Bart Mart E-commerce Web App",
  description: "Generated by create next app",
=======
  title: "Bart Mart E-commerce web app",
  description: "A project on e-commerce application using React",
>>>>>>> 1b51ae8ea8e08596ad8bbed7460a51867efd4679
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
<<<<<<< HEAD
=======
        <div className="min-h-screen">

>>>>>>> 1b51ae8ea8e08596ad8bbed7460a51867efd4679
        {children}
        </div>

        <Footer/>
      </body>
    </html>
  );
}
